# This file created by conda-build 3.18.9
# meta.yaml template originally from:
# C:\ci\containers\000021ljk4p\tmp\build\80754af9\rsync-recipes\jupyter_client-5.3.3-python_3.7-on-winbuilder, last modified Wed Sep 25 14:46:54 2019
# ------------------------------------------------

package:
    name: jupyter_client
    version: 5.3.3
source:
    sha256: f406f214f9daa92be110d5b83d62f3451ffc73d3522db7350f0554683533ab18
    url: https://pypi.io/packages/source/j/jupyter_client/jupyter_client-5.3.3.tar.gz
build:
    entry_points:
        - jupyter-kernel = jupyter_client.kernelapp:main
        - jupyter-kernelspec = jupyter_client.kernelspecapp:KernelSpecApp.launch_instance
        - jupyter-run = jupyter_client.runapp:main
    number: '1'
    script: C:\ci\jupyter_client_1569447674618\_h_env\python.exe -m pip install .
        --no-deps -vv
    string: py37_1
requirements:
    host:
        - ca-certificates 2019.8.28 0
        - certifi 2019.9.11 py37_0
        - openssl 1.1.1d he774522_0
        - pip 19.2.3 py37_0
        - python 3.7.4 h5263a28_0
        - setuptools 41.2.0 py37_0
        - sqlite 3.29.0 he774522_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_0
        - wheel 0.33.6 py37_0
        - wincertstore 0.2 py37_0
    run:
        - jupyter_core
        - python >=3.7,<3.8.0a0
        - python-dateutil >=2.1
        - pywin32
        - pyzmq >=13
        - tornado >=4.1
        - traitlets
test:
    commands:
        - jupyter kernelspec list
        - jupyter run -h
    imports:
        - jupyter_client
about:
    description: 'jupyter client contains the reference implementation of the Jupyter

        protocol.It also provides Python API for starting, managing and

        communicating with Jupyter kernels.

        '
    dev_url: https://github.com/jupyter/jupyter_client
    doc_source_url: https://github.com/jupyter/jupyter_client/blob/master/docs/index.rst
    doc_url: http://jupyter-client.readthedocs.org/
    home: http://jupyter.org
    license: BSD 3-clause
    license_file: COPYING.md
    summary: Jupyter protocol implementation and client libraries
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - SylvainCorlay
        - carreau
        - jakirkham
        - minrk
        - ocefpaf
        - pelson
